---
title: "R Survival Analysis"
output: html_notebook
---

### Libraries
```{r}
library(tidyverse)
library(finalfit)
library(patchwork)
library(magrittr)
library(broom)
library(ggplot2)
library(GGally)
library(lme4)
library(dplyr)
library(forcats)
library(survival)
library(survminer)
library(lubridate)
theme_set(theme_bw())
```

### Time-to-event data and survival
```{r}
melanoma <- boot::melanoma
glimpse(melanoma)
missing_glimpse(melanoma)
ff_glimpse(melanoma)
```

### Recode the data
```{r}
melanoma <- melanoma %>%
  mutate(
    # Overall survival
    status_os = if_else(status == 2, 0, # "still alive"
                       1), # "died of melanoma" or "died of other causes"
    
    # Diease-specific survival
    status_dss = if_else(status == 2, 0, # "still alive"
                        if_else(status == 1, 1, # "died of melanoma"
                               0)), # "died of other causes is censored"
    
    # Competing risks regression
    status_crr = if_else(status == 2, 0, # "still alive"
                        if_else(status == 1, 1, # "died of melanoma"
                               2)), # "died of other causes"
    
    # Label and recode other variables
    age = ff_label(age, "Age (years)"), # ff_label table friendly  labels
    thickness = ff_label(thickness, "Tumour thickness (mm)"),
    sex = factor(sex) %>% 
      fct_recode("Male" = "1", 
                 "Female" = "0") %>% 
      ff_label("Sex"),
    ulcer = factor(ulcer) %>% 
      fct_recode("No" = "0",
                 "Yes" = "1") %>% 
      ff_label("Ulcerated tumour")
  )
```
### Kaplan Meier survival estimator
```{r}
survival_object <- melanoma %$% 
    Surv(time, status_os)
head(survival_object)# + marks censoring, in this case "Alive"

# Expressing time in years
survival_object <- melanoma %$% 
    Surv(time/365, status_os)

# Overall survival in whole cohort
my_survfit <- survfit(survival_object ~ 1, data = melanoma)
my_survfit # 205 patients, 71 events

summary(my_survfit, times = c(0, 1, 2, 3, 4, 5))
```
```{r}
dependent_os <- "Surv(time/365, status_os)"
explanatory  <- c("ulcer")

melanoma %>% 
    surv_plot(dependent_os, explanatory, pval = TRUE)
```

### Cox proportional hazards regression
```{r}
coxph(Surv(time, status_os) ~ age + sex + thickness + ulcer, data = melanoma) %>% 
  summary()

print('*************************')
dependent_os  <- "Surv(time, status_os)"
dependent_dss <- "Surv(time, status_dss)"
dependent_crr <- "Surv(time, status_crr)"
explanatory   <- c("age", "sex", "thickness", "ulcer")

melanoma %>% 
    finalfit(dependent_os, explanatory)
print('*************************')
melanoma %>% 
    finalfit(dependent_os, explanatory, add_dependent_label = FALSE) %>% 
    rename("Overall survival" = label) %>% 
    rename(" " = levels) %>% 
    rename("  " = all)

print('*************************')
explanatory_multi <- c("age", "thickness", "ulcer")
melanoma %>% 
    finalfit(dependent_os, explanatory, 
             explanatory_multi, keep_models = TRUE)

explanatory <- c("age", "sex", "thickness", "ulcer", "year")
melanoma %>% 
    coxphmulti(dependent_os, explanatory) %>% 
    cox.zph() %>% 
    {zph_result <<- .} %>% 
    plot(var=5)

zph_result
```
```{r}
explanatory <- c("age", "sex", "ulcer", "thickness", 
               "strata(year)")
melanoma %>% 
    finalfit(dependent_os, explanatory)
```
```{r}
# Simulate random hospital identifier
melanoma <- melanoma %>% 
    mutate(hospital_id = c(rep(1:10, 20), rep(11, 5)))

# Cluster model
explanatory <- c("age", "sex", "thickness", "ulcer", 
                "cluster(hospital_id)")
melanoma %>% 
    finalfit(dependent_os, explanatory)
```
```{r}
# Frailty model
explanatory <- c("age", "sex", "thickness", "ulcer", 
                "frailty(hospital_id)")
melanoma %>% 
    finalfit(dependent_os, explanatory)
```

```{r}
melanoma %>% 
    hr_plot(dependent_os, explanatory)
```

#### Competing risks regression
```{r}
explanatory   <- c("age", "sex", "thickness", "ulcer")
dependent_dss <- "Surv(time, status_dss)"
dependent_crr <- "Surv(time, status_crr)"

melanoma %>%
    # Summary table
  summary_factorlist(dependent_dss, explanatory, 
                     column = TRUE, fit_id = TRUE) %>%
    # CPH univariable
      ff_merge(
    melanoma %>%
      coxphmulti(dependent_dss, explanatory) %>%
      fit2df(estimate_suffix = " (DSS CPH univariable)")
    ) %>%
    # CPH multivariable
  ff_merge(
    melanoma %>%
      coxphmulti(dependent_dss, explanatory) %>%
      fit2df(estimate_suffix = " (DSS CPH multivariable)")
    ) %>%
    # Fine and Gray competing risks regression
  ff_merge(
    melanoma %>%
      crrmulti(dependent_crr, explanatory) %>%
      fit2df(estimate_suffix = " (competing risks multivariable)")
    ) %>%
  select(-fit_id, -index) %>%
  dependent_label(melanoma, "Survival")
```
#### Dates to survival time
```{r}
first_date <- ymd("1966-01-01")           # create made-up dates for operations
last_date  <- first_date + 
  days(nrow(melanoma)-1)                  # every day from 1-Jan 1966
operation_date <- 
  seq(from = first_date, 
      to = last_date, by = "1 day")       # create dates

melanoma$operation_date <- operation_date # add sequence to melanoma dataset

melanoma <- melanoma %>% 
  mutate(censoring_date = operation_date + days(time))

# (Same as doing:):
melanoma$censoring_date <- melanoma$operation_date + days(melanoma$time)
melanoma <- melanoma %>% 
  mutate(time_days = censoring_date - operation_date)

# This doesn't work 
# Surv(melanoma$time_days, melanoma$status==1)
melanoma <- melanoma %>% 
  mutate(time_days_numeric = as.numeric(time_days))

```
#### Exercises
```{r}
survfit(formula = survival_object ~ ulcer, data = melanoma)
```
```{r}
# Fit model
my_hazard = coxph(survival_object ~ sex + ulcer + age + thickness, data=melanoma)
summary(my_hazard)

# Melanoma thickness has a HR 1.11 (1.03 to 1.18). 
# This is interpretted as a 11% increase in the
# risk of death at any time for each 1 mm increase in thickness. 

# Check assumptions
ph = cox.zph(my_hazard)
ph
# GLOBAL shows no overall violation of assumptions.
# Plot Schoenfield residuals to evaluate PH
plot(ph, var=4)
```

