---
title: "R Summarizing data"
output: html_notebook
---

### Packages
```{r}
library(tidyverse)
library(scales)
```


### Get the data
```{r}
gbd_full <- read_csv("data/global_burden_disease_cause-year-sex-income.csv")
gbd2017 <- gbd_full %>% 
  filter(year == 2017)
gbd2017
```
### Plot the data
```{r}
gbd2017 %>% 
  # without the mutate(... = fct_relevel()) 
  # the panels get ordered alphabetically
  mutate(income = fct_relevel(income,
                              "Low",
                              "Lower-Middle",
                              "Upper-Middle",
                              "High")) %>% 
  # defining the variables using ggplot(aes(...)):
  ggplot(aes(x = sex, y = deaths_millions, fill = cause)) +
  # type of geom to be used: column (that's a type of barplot):
  geom_col(position = "dodge") +
  # facets for the income groups:
  facet_wrap(~income, ncol = 4) +
  # move the legend to the top of the plot (default is "right"):
  theme(legend.position = "top")
```
### Aggregation group_by(), summarise()
```{r}
gbd2017$deaths_millions %>% sum()

gbd2017 %>% 
  summarise(sum(deaths_millions))

gbd2017 %>% 
  group_by(cause) %>% 
  summarise(sum(deaths_millions))

gbd2017 %>% 
  group_by(cause, sex) %>% 
  summarise(sum(deaths_millions))
```
### Add new columns, mutate()
```{r}
gbd2017 %>% 
  group_by(cause, sex) %>% 
  summarise(deaths_per_group = sum(deaths_millions)) %>% 
  ungroup() %>% 
  mutate(deaths_total = sum(deaths_per_group))

gbd2017_summarised <- gbd2017 %>% 
  group_by(cause, sex) %>% 
  summarise(deaths_per_group = sum(deaths_millions)) %>% 
  ungroup() %>% 
  mutate(deaths_total    = sum(deaths_per_group),
         deaths_relative = percent(deaths_per_group/deaths_total))
gbd2017_summarised

gbd2017_summarised %>% 
  mutate(deaths_relative = deaths_per_group/deaths_total)
```
### Summarise vs Mutate
```{r}
gbd_summarised <- gbd2017 %>% 
  group_by(cause, sex) %>% 
  summarise(deaths_per_group = sum(deaths_millions)) %>% 
  arrange(sex)
gbd_summarised


gbd_summarised_sex <- gbd_summarised %>% 
  group_by(sex) %>% 
  summarise(deaths_per_sex = sum(deaths_per_group))
gbd_summarised_sex
full_join(gbd_summarised, gbd_summarised_sex)

gbd_summarised %>% 
  group_by(sex) %>% 
  mutate(deaths_per_sex = sum(deaths_per_group))
```
```{r}
gbd2017 %>% 
  group_by(cause, sex) %>% 
  summarise(deaths_per_group = sum(deaths_millions)) %>% 
  group_by(sex) %>% 
  mutate(deaths_per_sex  = sum(deaths_per_group),
         sex_cause_perc = percent(deaths_per_group/deaths_per_sex)) %>% 
  arrange(sex, deaths_per_group)
```
### Arithmetic functions
```{r}
mynumbers <- c(1, 2, NA)
sum(mynumbers)
sum(mynumbers, na.rm = TRUE)
```
### Select() columns
```{r}
gbd_2rows <- gbd_full %>% 
  slice(1:2)
gbd_2rows

gbd_2rows %>% 
  select(cause, deaths_millions)

gbd_2rows %>% 
  select(cause, deaths = deaths_millions)

gbd_2rows %>% 
  rename(deaths = deaths_millions)

# reordering cols
gbd_2rows %>% 
  select(year, sex, income, cause, deaths_millions)
gbd_2rows %>% 
  select(year, sex, everything())
gbd_2rows %>% 
  select(starts_with("deaths"))
```
### Reshaping data, long vs wide format
```{r}
gbd_wide <- read_csv("data/global_burden_disease_wide-format.csv")
gbd_long <- read_csv("data/global_burden_disease_cause-year-sex.csv")

gbd_long
gbd_wide

gbd_long %>% 
  pivot_wider(names_from = year, values_from = deaths_millions)

gbd_long %>% 
  pivot_wider(names_from = sex, values_from = deaths_millions) %>%
  mutate(Male - Female)

gbd_long %>% 
  pivot_wider(names_from = c(sex, year), values_from = deaths_millions)

gbd_wide %>% 
  pivot_longer(matches("Female|Male"), 
               names_to = "sex_year", 
               values_to = "deaths_millions") %>% 
  slice(1:6)

gbd_wide %>% 
  select(matches("Female|Male"))

gbd_wide %>% 
  # same pivot_longer as before
  pivot_longer(matches("Female|Male"), 
               names_to = "sex_year", 
               values_to = "deaths_millions") %>% 
  separate(sex_year, into = c("sex", "year"), sep = "_", convert = TRUE)
```
### Arrange() rows
```{r}
gbd_long %>% 
  arrange(deaths_millions) %>% 
  # first 3 rows just for printing:
  slice(1:3)

gbd_long %>% 
  arrange(-deaths_millions) %>% 
  slice(1:3)

gbd_long %>% 
  arrange(desc(sex)) %>% 
  # printing rows 1, 2, 11, and 12
  slice(1,2, 11, 12)

gbd_factored <- gbd_long %>% 
  mutate(cause = factor(cause))

gbd_factored

gbd_factored$cause %>% levels()
gbd_factored <- gbd_factored %>% 
  mutate(cause = cause %>% 
           fct_relevel("Injuries"))
gbd_factored$cause %>% levels()
gbd_factored %>% 
  arrange(cause)
```
### Exercises
```{r}
gbd_long <- read_csv("data/global_burden_disease_cause-year-sex.csv")
gbd_long
```

```{r}
gbd_long %>% pivot_wider(names_from = cause, 
                         values_from = deaths_millions)
gbd_long
```
```{r}
gbd_full <- read_csv("data/global_burden_disease_cause-year-sex-income.csv")
glimpse(gbd_full)

summary_data1 <- 
  gbd_full %>% 
  group_by(year) %>% 
  summarise(total_per_year = sum(deaths_millions))
summary_data1

summary_data2 <- 
  gbd_full %>% 
  group_by(year, cause) %>% 
  summarise(total_per_cause = sum(deaths_millions))
summary_data2
```

```{r}
full_join(summary_data1, summary_data2) %>% 
  mutate(percentage = percent(total_per_cause/total_per_year))
```
```{r}
gbd_full %>% 
  # aggregate to deaths per cause per year using summarise()
  group_by(year, cause) %>% 
  summarise(total_per_cause = sum(deaths_millions)) %>% 
  # then add a column of yearly totals using mutate()
  group_by(year) %>% 
  mutate(total_per_year = sum(total_per_cause)) %>% 
  # add the percentage column
  mutate(percentage = percent(total_per_cause/total_per_year)) %>% 
  # select the final variables for better vieweing
  select(year, cause, percentage) %>% 
  pivot_wider(names_from = cause, values_from = percentage)
```
```{r}
gbd_full %>% 
  filter(year == 1990) %>% 
  group_by(income, sex) %>% 
  summarise(total_deaths = sum(deaths_millions)) %>% 
  pivot_wider(names_from = income, values_from = total_deaths)
```

